-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 23:51:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema WDS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WDS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WDS` DEFAULT CHARACTER SET utf8 ;
USE `WDS` ;

-- -----------------------------------------------------
-- Table `WDS`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WDS`.`user` ;

CREATE TABLE IF NOT EXISTS `WDS`.`user` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_username` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WDS`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WDS`.`customer` ;

CREATE TABLE IF NOT EXISTS `WDS`.`customer` (
  `cid` BIGINT NOT NULL AUTO_INCREMENT,
  `cfirstname` VARCHAR(30) NOT NULL,
  `clastname` VARCHAR(30) NOT NULL,
  `cgender` CHAR(1) NULL DEFAULT NULL,
  `cmaritality` CHAR(1) NOT NULL,
  `cinstype` CHAR(1) NOT NULL,
  `chouse` INT NOT NULL,
  `cstreet` VARCHAR(30) NOT NULL,
  `ccity` VARCHAR(30) NOT NULL,
  `cstate` VARCHAR(2) NOT NULL,
  `czipcode` INT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`cid`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_customer`
    FOREIGN KEY (`user_id`)
    REFERENCES `WDS`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WDS`.`insurance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WDS`.`insurance` ;

CREATE TABLE IF NOT EXISTS `WDS`.`insurance` (
  `insid` BIGINT NOT NULL AUTO_INCREMENT,
  `insstartdate` DATETIME NOT NULL,
  `insenddate` DATETIME NOT NULL,
  `inspremium` DECIMAL(10,2) NOT NULL,
  `cid` BIGINT NOT NULL,
  PRIMARY KEY (`insid`),
  INDEX `cid_idx` (`cid` ASC) VISIBLE,
  CONSTRAINT `fk_customer_ins`
    FOREIGN KEY (`cid`)
    REFERENCES `WDS`.`customer` (`cid`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WDS`.`auto_ins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WDS`.`auto_ins` ;

CREATE TABLE IF NOT EXISTS `WDS`.`auto_ins` (
  `insid` BIGINT NOT NULL,
  `vin` VARCHAR(20) NOT NULL,
  `vmake` VARCHAR(30) NOT NULL,
  `vmodel` VARCHAR(30) NULL DEFAULT NULL,
  `vyear` INT NOT NULL,
  `vstatus` CHAR(1) NOT NULL,
  `licenseno` VARCHAR(10) NOT NULL,
  `driverfirstname` VARCHAR(30) NOT NULL,
  `driverlastname` VARCHAR(30) NOT NULL,
  `driverbirthdate` DATETIME NOT NULL,
  PRIMARY KEY (`insid`),
  CONSTRAINT `fk_ins_auto`
    FOREIGN KEY (`insid`)
    REFERENCES `WDS`.`insurance` (`insid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `WDS`.`home_ins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WDS`.`home_ins` ;

CREATE TABLE IF NOT EXISTS `WDS`.`home_ins` (
  `insid` BIGINT NOT NULL,
  `hpurchasedate` DATETIME NOT NULL,
  `hvalue` DECIMAL(10,2) NOT NULL,
  `harea` DECIMAL(8,2) NOT NULL,
  `htype` CHAR(1) NOT NULL,
  `hfire` CHAR(1) NOT NULL,
  `hsecurity` CHAR(1) NOT NULL,
  `hpool` CHAR(1) NOT NULL,
  `hbasement` CHAR(1) NOT NULL,
  PRIMARY KEY (`insid`),
  CONSTRAINT `fk_ins_home`
    FOREIGN KEY (`insid`)
    REFERENCES `WDS`.`insurance` (`insid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
